/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by Keycloakify

export type ThemeName = "onyxia";

export const themeNames: ThemeName[] = ["onyxia"];

export type KcEnvName =
    | "ONYXIA_RESOURCES_ALLOWED_ORIGINS"
    | "ONYXIA_HEADER_TEXT_BOLD"
    | "ONYXIA_HEADER_TEXT_FOCUS"
    | "ONYXIA_PALETTE_OVERRIDE"
    | "ONYXIA_TAB_TITLE";

export const kcEnvNames: KcEnvName[] = [
    "ONYXIA_RESOURCES_ALLOWED_ORIGINS",
    "ONYXIA_HEADER_TEXT_BOLD",
    "ONYXIA_HEADER_TEXT_FOCUS",
    "ONYXIA_PALETTE_OVERRIDE",
    "ONYXIA_TAB_TITLE"
];

export const kcEnvDefaults: Record<KcEnvName, string> = {
    "ONYXIA_RESOURCES_ALLOWED_ORIGINS": "*",
    "ONYXIA_HEADER_TEXT_BOLD": "",
    "ONYXIA_HEADER_TEXT_FOCUS": "",
    "ONYXIA_PALETTE_OVERRIDE": "",
    "ONYXIA_TAB_TITLE": "Onyxia"
};

/* prettier-ignore-end */
