// This file is auto-generated by the `update-kc-gen` command. Do not edit it manually.
// Hash: 8c46abfd27809aa4296924b8a6789a2cdfa78f83063b0b9a46d03777f9bfc52b

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

import { lazy, Suspense, type ReactNode } from "react";

export type ThemeName = "onyxia";

export const themeNames: ThemeName[] = ["onyxia"];

export type KcEnvName =
    | "ONYXIA_RESOURCES_ALLOWED_ORIGINS"
    | "ONYXIA_HEADER_TEXT_BOLD"
    | "ONYXIA_HEADER_TEXT_FOCUS"
    | "ONYXIA_PALETTE_OVERRIDE"
    | "ONYXIA_TAB_TITLE";

export const kcEnvNames: KcEnvName[] = [
    "ONYXIA_RESOURCES_ALLOWED_ORIGINS",
    "ONYXIA_HEADER_TEXT_BOLD",
    "ONYXIA_HEADER_TEXT_FOCUS",
    "ONYXIA_PALETTE_OVERRIDE",
    "ONYXIA_TAB_TITLE"
];

export const kcEnvDefaults: Record<KcEnvName, string> = {
    ONYXIA_RESOURCES_ALLOWED_ORIGINS: "*",
    ONYXIA_HEADER_TEXT_BOLD: "",
    ONYXIA_HEADER_TEXT_FOCUS: "",
    ONYXIA_PALETTE_OVERRIDE: "",
    ONYXIA_TAB_TITLE: "Onyxia"
};

/**
 * NOTE: Do not import this type except maybe in your entrypoint.
 * If you need to import the KcContext import it either from src/login/KcContext.ts or src/account/KcContext.ts.
 * Depending on the theme type you are working on.
 */
export type KcContext = import("./login/KcContext").KcContext;

declare global {
    interface Window {
        kcContext?: KcContext;
    }
}

export const KcLoginPage = lazy(() => import("./login/KcPage"));

export function KcPage(props: { kcContext: KcContext; fallback?: ReactNode }) {
    const { kcContext, fallback } = props;
    return (
        <Suspense fallback={fallback}>
            {(() => {
                switch (kcContext.themeType) {
                    case "login":
                        return <KcLoginPage kcContext={kcContext} />;
                }
            })()}
        </Suspense>
    );
}
