{{- if .Values.api.schemas.enabled }}
{{- range .Values.api.schemas.files }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: json-config-{{ .relativePath | sha256sum | trunc 8 }}
data:
  {{ .relativePath | base }}: |-
{{ .content | indent 4 }}
---
{{- end }}
{{- end }}
