apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "onyxia.fullname" . }}
  labels:
    app: {{ template "onyxia.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  server.servlet.context-path: {{ .Values.api.contextPath | quote }}
{{- if .Values.api.env }}
{{- range $key, $value := .Values.api.env }}
  {{ $key }}: {{ $value | quote }}
{{- end -}}
{{- end -}}
{{- if .Values.api.regions }}
  regions: {{ .Values.api.regions | toJson | quote }}
{{- end}}
{{- if .Values.api.catalogs }}
  catalogs: {{ .Values.api.catalogs | toJson | quote }}
{{- end}}