apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "onyxia.api.fullname" . }}
  labels:
    {{- include "onyxia.api.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      {{- include "onyxia.api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        {{- include "onyxia.api.selectorLabels" . | nindent 8 }}
{{- with .Values.api.podLabels }}
{{ toYaml . | indent 8 }}
{{- end }}
    spec:
    {{- with .Values.hostAliases }}
      hostAliases:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.api.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "onyxia.api.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.api.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.api.securityContext | nindent 12 }}
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
          envFrom:
            - configMapRef:
                name: {{ template "onyxia.fullname" . }}
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.api.containerPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .Values.api.contextPath }}/public/healthcheck
              port: http
          readinessProbe:
            httpGet:
              path: {{ .Values.api.contextPath }}/public/healthcheck
              port: http
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
          {{- if .Values.api.extraVolumeMounts }}
          volumeMounts: {{- toYaml .Values.api.extraVolumeMounts | nindent 12 }}
          {{- end }}
      {{- with .Values.api.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.api.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.api.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- if .Values.api.extraVolumes }}
      volumes: {{- toYaml .Values.api.extraVolumes | nindent 6 }}
    {{- end }}
