apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "onyxia.api.fullname" . }}
  labels:
    {{- include "onyxia.api.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      {{- include "onyxia.api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        {{- include "onyxia.api.selectorLabels" . | nindent 8 }}
{{- with .Values.api.podLabels }}
{{ toYaml . | indent 8 }}
{{- end }}
    spec:
    {{- with .Values.hostAliases }}
      hostAliases:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.api.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "onyxia.api.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.api.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.api.securityContext | nindent 12 }}
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
          envFrom:
            - configMapRef:
                name: {{ template "onyxia.fullname" . }}
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.api.containerPort }}
              protocol: TCP
        {{- if .Values.api.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.api.contextPath }}{{ .Values.api.livenessProbe.path }}
              port: http
            failureThreshold: {{ .Values.api.livenessProbe.failureThreshold }}
            periodSeconds: {{ .Values.api.livenessProbe.periodSeconds }}
            successThreshold: {{ .Values.api.livenessProbe.successThreshold }}
            timeoutSeconds: {{ .Values.api.livenessProbe.timeoutSeconds }}
        {{- end }}
        {{- if .Values.api.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.api.contextPath }}{{ .Values.api.readinessProbe.path }}
              port: http
            failureThreshold: {{ .Values.api.readinessProbe.failureThreshold }}
            periodSeconds: {{ .Values.api.readinessProbe.periodSeconds }}
            successThreshold: {{ .Values.api.readinessProbe.successThreshold }}
            timeoutSeconds: {{ .Values.api.readinessProbe.timeoutSeconds }}
        {{- end }}
        {{- if .Values.api.startupProbe.enabled }}
          startupProbe:
            httpGet:
              path: {{ .Values.api.contextPath }}{{ .Values.api.startupProbe.path }}
              port: http
            failureThreshold: {{ .Values.api.startupProbe.failureThreshold }}
            periodSeconds: {{ .Values.api.startupProbe.periodSeconds }}
            successThreshold: {{ .Values.api.startupProbe.successThreshold }}
            timeoutSeconds: {{ .Values.api.startupProbe.timeoutSeconds }}
        {{- end }}
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
          {{- if or .Values.api.schemas.enabled .Values.api.extraVolumes }}
          volumeMounts:
            {{- if .Values.api.schemas.enabled }}
            {{- $path := .Values.api.schemas.rootPath -}}
            {{- $subpath := .Values.api.schemas.subPathDefault -}}
            {{- $fullname := include "onyxia.fullname" . -}}
            {{- range .Values.api.schemas.files }}
            - name: {{ $fullname }}-{{ printf "%s %s" .relativePath "default" | sha256sum | trunc 8 }}
              mountPath: {{ printf "%s%s/%s" $path $subpath .relativePath }}
              subPath: {{ .relativePath | base }}
            {{- end }}
            {{- $subpath := .Values.api.schemas.subPathRole -}}
            {{- range .Values.api.schemas.roles }}
            {{- $role := .roleName -}}
            {{- range .files }}           
            - name: {{ $fullname }}-{{ printf "%s %s %s" .relativePath "role" $role | sha256sum | trunc 8 }}
              mountPath: {{ printf "%s%s/%s/%s" $path $subpath $role .relativePath }}
              subPath: {{ .relativePath | base }}    
            {{- end }}
            {{- end }}
            {{- end }}
            {{- if .Values.api.extraVolumeMounts }}
            {{- toYaml .Values.api.extraVolumeMounts | nindent 12 }}
            {{- end }}
          {{- end }}
      {{- with .Values.api.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.api.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.api.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      {{- if or .Values.api.schemas.enabled .Values.api.extraVolumes }}
      volumes:
        {{- if .Values.api.schemas.enabled }}
        {{- $fullname := include "onyxia.fullname" . -}}
        {{- range .Values.api.schemas.files }}
        - name: {{ $fullname }}-{{ printf "%s %s" .relativePath "default" | sha256sum | trunc 8 }}
          configMap:
            name: {{ $fullname }}-{{ printf "%s %s" .relativePath "default" | sha256sum | trunc 8 }}
        {{- end }}
        {{- range .Values.api.schemas.roles }}
        {{- $role := .roleName -}}
        {{- range .files }}
        - name: {{ $fullname }}-{{ printf "%s %s %s" .relativePath "role" $role | sha256sum | trunc 8 }}
          configMap:
            name: {{ $fullname }}-{{ printf "%s %s %s" .relativePath "role" $role | sha256sum | trunc 8 }}        
        {{- end }}
        {{- end }}
        {{- end }}
        {{- if .Values.api.extraVolumes }}
        {{- toYaml .Values.api.extraVolumes | nindent 8 }}
        {{- end }}
      {{- end }}
    {{- if .Values.api.priorityClassName }}
      priorityClassName: "{{ .Values.api.priorityClassName }}"
    {{- end }}
