{{- if .Values.onboarding.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "onyxia.onboarding.serviceAccountName" . }}
  labels:
    {{- include "onyxia.onboarding.labels" . | nindent 4 }}
  {{- with .Values.onboarding.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.onboarding.serviceAccount.automount }}
{{- end }}
