{{- if .Values.onboarding.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "onyxia.onboarding.fullname" . }}
  labels:
    {{- include "onyxia.onboarding.labels" . | nindent 4 }}
spec:
  type: {{ .Values.onboarding.service.type }}
  ports:
    - port: {{ .Values.onboarding.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "onyxia.onboarding.selectorLabels" . | nindent 4 }}
{{- end }}