
import * as fs from "fs";
import * as path from "path";
import { inputNames, getInputDescription, getInputDefault } from "../src/inputHelper";
import { outputNames, getOutputDescription } from "../src/outputHelper";
import { id } from "tsafe/id";
import { exclude } from "tsafe/exclude";


const projectRoot = path.join(__dirname, "..");

const packageJsonParsed = require(path.join(projectRoot, "package.json"));

fs.writeFileSync(
    path.join(projectRoot, "action.yml"),
    Buffer.from([
        `# This file is generated by ${path.basename(__filename)}, do not edit manually`,
        ``,
        `name: '${packageJsonParsed["name"]}'`,
        `description: '${packageJsonParsed["description"]}'`,
        `author: '${packageJsonParsed["author"]}'`,
        `inputs:`,
        ...inputNames.map((inputName, i) => [
            `  ${inputName}:`,
            `    required: ${i === 0 ? "true" : "false"}`,
            `    description: '${getInputDescription(inputName).replace(/'/g,"''")}'`,
            ...[getInputDefault(inputName)].filter(exclude(undefined)).map(s=>`    default: '${s.replace(/'/g,"''")}'`)
        ].join("\n")),
        ...(id<readonly string[]>(outputNames).length === 0 ? [] : [`outputs:`]),
        ...outputNames.map((outputName, i) => [
            `  ${outputName}:`,
            `    description: '${getOutputDescription(outputName).replace(/'/g,"''")}'`
        ].join("\n")),
        `runs:`,
        `  using: 'node20'`,
        `  main: '${packageJsonParsed.main}'`,
    ].join("\n"), "utf8")
);
